# R2 R1
GEMINI_API_KEY_META1 = ""
GEMINI_API_KEY_META2 = ""

# R3 R R4 R5 R6
GEMINI_API_KEY_ITEMS1 = ""
GEMINI_API_KEY_ITEMS2 = ""
GEMINI_API_KEY_ITEMS3 = ""
GEMINI_API_KEY_ITEMS4 = ""
GEMINI_API_KEY_ITEMS5 = ""
